version: '3'

services:
  py:
    build: .
#    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

  db:
    image: postgres
    networks:
      - my-network
    restart: always
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    networks:
      - my-network
    restart: always
  
  nginx:
    image: nginx
    restart: always
    networks:
      - my-network
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./certbot_etc:/etc/letsencrypt
      - ./certbot_var:/var/lib/letsencrypt
      - ./app/static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - nginx_html:/usr/share/nginx/html
    depends_on:
      - py
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    command: nginx -g 'daemon off;'
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot_etc:/etc/letsencrypt
      - ./certbot_var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html -d example.com -d www.example.com --email youremail@example.com --agree-tos --non-interactive

volumes:
  db_data:
  certbot_etc:
  certbot_var:
  nginx_conf:
  nginx_html:

networks:
  my-network: